Store tx on localstorage
rsksmart/multisig-sample-app pull request #35
Opened 2021-07-19 13:54 UTC by antomor

## What

- Store the transactions on local storage to retrieve them on app reload
- merge the locally stored transactions with the ones retrieved from the contract and the server.

## Why

- we can reload the application without losing the transactions created (and not yet approved)
- we can store the transactions even before publishing them
- we can keep track of the signer the signed the transaction off-chain

2021-07-19 17:18 UTC, ilanolkies commented on src/helpers/missingTypes.ts
> +// The package '@gnosis.pm/safe-service-client' doesn't export the type SafeMultisigConfirmationResponse
Should we rise an issue in their repo?

2021-07-19 18:21 UTC, ilanolkies reviewed
Works for me! @jessgusclark can check code perspective.

2021-07-21 08:12 UTC, antomor commented on src/helpers/missingTypes.ts
> +// The package '@gnosis.pm/safe-service-client' doesn't export the type SafeMultisigConfirmationResponse
Yep, I think so

2021-07-21 10:12 UTC, jessgusclark commented
An issue with checksums (perhaps) and new safes

1. create a new safe
2. Fund the safe with the faucet
3. Create a transaction
4. refresh page.
5. transaction does not show up in UI, but is in localstorage:

![Screen Shot 2021-07-21 at 1 11 39 PM](https://user-images.githubusercontent.com/766679/126472547-98a32f50-7c01-47c6-956f-72deea329607.png)

2021-07-21 10:16 UTC, jessgusclark commented
An issue with a rejection transaction that is not executed showing up as pending after refresh

1. existing safe from above
2. create a transfer transaction
3. create a rejection transaction
4. sign the transfer transaction off-chain
5. refresh (probably not needed but I wanted to check both transactions were saved)
6. execute the transfer transaction
7. see the two transactions sorted correctly into their tabs/buckets: executed and rejected
8. Refresh site
9. Rejection transaction shows up under "Pending Transactions" with a nonce of X even though the safe's nonce should be x+1

2021-07-21 10:17 UTC, jessgusclark requested changes
The code looks great and THANK YOU for fixing my spelling mistakes! I left two comments regarding issues that I found with the UX.

2021-07-21 11:04 UTC, antomor commented
> An issue with checksums (perhaps) and new safes
> 
>     1. create a new safe
> 
>     2. Fund the safe with the faucet
> 
>     3. Create a transaction
> 
>     4. refresh page.
> 
>     5. transaction does not show up in UI, but is in localstorage:
> 
> 
> ![Screen Shot 2021-07-21 at 1 11 39 PM](https://user-images.githubusercontent.com/766679/126472547-98a32f50-7c01-47c6-956f-72deea329607.png)

Thank you for pointing it out 🙏🏼  
I confirm that the issue is related to the safe address case.

2021-07-21 15:21 UTC, antomor commented
> An issue with a rejection transaction that is not executed showing up as pending after refresh
> 
>     1. existing safe from above
> 
>     2. create a transfer transaction
> 
>     3. create a rejection transaction
> 
>     4. sign the transfer transaction off-chain
> 
>     5. refresh (probably not needed but I wanted to check both transactions were saved)
> 
>     6. execute the transfer transaction
> 
>     7. see the two transactions sorted correctly into their tabs/buckets: executed and rejected
> 
>     8. Refresh site
> 
>     9. Rejection transaction shows up under "Pending Transactions" with a nonce of X even though the safe's nonce should be x+1

Although this particular use case is solved, I think a better solution would be to publish all the transactions, but it's not possible with the current version of the `safe-transaction-service` client.

2021-07-22 00:52 UTC, ilanolkies commented
Maybe the UX is better if we add a new tab for the “not submitted” transactions. Instead of merging local storage and tx service, we can do one list for each. The “not submitted” ones would allow to sign on chain or off chain, and submit.

2021-07-22 09:23 UTC, jessgusclark commented
@ilanolkies @antomor 

Sorry, I don't understand the issue with publishing two transactions with the same nonce to the service. I thought this was possible.

Nonetheless, How about a different scenario:

1. create a transaction
2. sign it off-chain
3. publish it to the transaction service
4. refresh
5. create rejection transaction
6. sign rejection transaction
7. execute rejection transaction
4. refresh site
5. the "send value" transaction shows up twice under "Rejected" and the executed [rejected] transaction is missing. The nonce is set to 1 so a transaction with the nonce of 0 was executed.


When retrieving the transactions from the service or localStorage, the UX should check if the nonce of the transaction is less than the safe's nonce. If true, and the transaction is not executed, then the transaction is "rejected".

2021-07-23 10:31 UTC, antomor commented
> @ilanolkies @antomor
> 
> Sorry, I don't understand the issue with publishing two transactions with the same nonce to the service. I thought this was possible.

The problem here was related to the `safe-transaction-service` client, that requires the signature as mandatory parameter.
We can circumvent that issue by performing the API request directly, without using the client.

> 
> Nonetheless, How about a different scenario:
> 
>     1. create a transaction
> 
>     2. sign it off-chain
> 
>     3. publish it to the transaction service
> 
>     4. refresh
> 
>     5. create rejection transaction
> 
>     6. sign rejection transaction
> 
>     7. execute rejection transaction
> 
>     8. refresh site
> 
>     9. the "send value" transaction shows up twice under "Rejected" and the executed [rejected] transaction is missing. The nonce is set to 1 so a transaction with the nonce of 0 was executed.
> 
> 
> When retrieving the transactions from the service or localStorage, the UX should check if the nonce of the transaction is less than the safe's nonce. If true, and the transaction is not executed, then the transaction is "rejected".

Although publishing the transaction does solve a lot of misalignment issues, this situation described by @jessgusclark can still occur. This is due to the fact that the service requires some time before updating the rejection transaction. 
So just after the transaction is executed, there will be two transactions in an undefined state:
- they look like they are pending, but they are not since that the safe nonce is greater
- they could be set as rejected, but actually, one of them is executed, and only the other one is rejected.
The situation is solved just after the server receives the update from the network (with the `trace_block` method).

2021-07-23 10:37 UTC, antomor commented
Since that we changed completely strategy and instead of storing transactions locally, we store them on the service, I'm replacing this PR with a new one: https://github.com/rsksmart/multisig-sample-app/pull/36

2021-07-23 10:37 UTC, closed without merging